### ISSUE TITLE
Not for Ender 5 Pro!

### ISSUE THREAD

**Issue by marc-gist** [3d-printing-canada/Ender-5-BL-Touch-Installation#2]
Don't use this version on the Ender 5 pro.  the z-axis steps are 2x on ender 5 pro (it has a different z-axis screw) so this version of the firmware will only move up 1/2 the correct amount, which of course your print layer 2+ will be gouging into the layer below.

**Comment by belgar35** [comment]
I just ran into this issue today after all my pain of trying to use faulty "official" drivers <sigh> over the weekend <curse you progisp.exe>, fortunately a fairly easy fix is available for marlin. I am printing now and it seems to have fixed the z steps issue, but no idea if enabling the TMC2208s had any effect.

In configuration.h file:

1) Change the "400" to "800" in "DEFAULT_AXIS_STEPS_PER_UNIT "

2) Enable the improved stepper motors by searching for "Stepper Drivers" section (line 645 in this build) 
Un-comment lines X, Y, Z, and E0_DRIVER_TYPE (by removing the double slashes "//")
and change the value to "TMC2208_STANDALONE" for each line you un-commented.

Note: 
I was using VS Code, and simply saved and compiled it, then had my .hex to flash. However if using Arduino IDE, you may need to add the "TMC2208" library (tools - manage libraries - type tmc2208 and click install).

With these changes you should have an "Ender 5 Pro" config/build in no time.

Actual file changes below:
1)
```
/**
 * Default Axis Steps Per Unit (steps/mm)
 * Override with M92
 *                                      X, Y, Z, E0 [, E1[, E2[, E3[, E4[, E5]]]]]
 */
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 800, 93 }
```
2)

```
/**
 * Stepper Drivers
 *
 * These settings allow Marlin to tune stepper driver timing and enable advanced options for
 * stepper drivers that support them. You may also override timing options in Configuration_adv.h.
 *
 * A4988 is assumed for unspecified drivers.
 *
 * Options: A4988, A5984, DRV8825, LV8729, L6470, TB6560, TB6600, TMC2100,
 *          TMC2130, TMC2130_STANDALONE, TMC2160, TMC2160_STANDALONE,
 *          TMC2208, TMC2208_STANDALONE, TMC2209, TMC2209_STANDALONE,
 *          TMC26X,  TMC26X_STANDALONE,  TMC2660, TMC2660_STANDALONE,
 *          TMC5130, TMC5130_STANDALONE, TMC5160, TMC5160_STANDALONE
 * :['A4988', 'A5984', 'DRV8825', 'LV8729', 'L6470', 'TB6560', 'TB6600', 'TMC2100', 'TMC2130', 'TMC2130_STANDALONE', 'TMC2160', 'TMC2160_STANDALONE', 'TMC2208', 'TMC2208_STANDALONE', 'TMC2209', 'TMC2209_STANDALONE', 'TMC26X', 'TMC26X_STANDALONE', 'TMC2660', 'TMC2660_STANDALONE', 'TMC5130', 'TMC5130_STANDALONE', 'TMC5160', 'TMC5160_STANDALONE']
 */
#define X_DRIVER_TYPE  TMC2208_STANDALONE
#define Y_DRIVER_TYPE  TMC2208_STANDALONE
#define Z_DRIVER_TYPE  TMC2208_STANDALONE
//#define X2_DRIVER_TYPE A4988
//#define Y2_DRIVER_TYPE A4988
//#define Z2_DRIVER_TYPE A4988
//#define Z3_DRIVER_TYPE A4988
#define E0_DRIVER_TYPE TMC2208_STANDALONE
//#define E1_DRIVER_TYPE A4988
//#define E2_DRIVER_TYPE A4988
//#define E3_DRIVER_TYPE A4988
//#define E4_DRIVER_TYPE A4988
//#define E5_DRIVER_TYPE A4988
```

**Comment by belgar35** [comment]
I made my own branch with the changes listed above (plus changed machine name to "Ender-5-Pro" ';)... @paulpenney let me know if there is any value in me pushing/publishing the branch

**Comment by Jean-Michel-90** [comment]
Hello @belgar35 ,
I 've neither found your branch in this repository nor the second part of you modivication (about stepper drivers) in config.h.
I had ever tried to modify step per unit for Z but this doesn't fix this issue...
Thanks for your help
